deeprvat_repo_dir: ../..

use_pretrained_models: True
pretrained_model_path : ../../pretrained_models

#Phenotypes to be used only for Association Testing
phenotypes_for_association_testing:
  - Apolipoprotein_A
  - Apolipoprotein_B
  - Calcium
  - Cholesterol
  - Red_blood_cell_erythrocyte_count
  - HDL_cholesterol
  - IGF_1
  - LDL_direct
  - Lymphocyte_percentage
  - Mean_platelet_thrombocyte_volume
  - Mean_corpuscular_volume
  - Mean_reticulocyte_volume
  - Neutrophill_count
  - Platelet_count
  - Platelet_crit
  - Platelet_distribution_width
  - SHBG
  - Standing_height
  - Total_bilirubin
  - Triglycerides
  - Urate

#File paths of necessary input files to DeepRVAT
gt_filename: genotypes.h5
variant_filename: variants.parquet
phenotype_filename: phenotypes.parquet
annotation_filename: annotations.parquet
gene_filename: protein_coding_genes.parquet

covariates: #x_phenotypes
  - age
  - age2
  - age_sex
  - genetic_sex
  - genetic_PC_1
  - genetic_PC_2
  - genetic_PC_3
  - genetic_PC_4
  - genetic_PC_5
  - genetic_PC_6
  - genetic_PC_7
  - genetic_PC_8
  - genetic_PC_9
  - genetic_PC_10
  - genetic_PC_11
  - genetic_PC_12
  - genetic_PC_13
  - genetic_PC_14
  - genetic_PC_15
  - genetic_PC_16
  - genetic_PC_17
  - genetic_PC_18
  - genetic_PC_19
  - genetic_PC_20

association_testing_data_thresholds:
  MAF: "< 1e-3"
  CADD_PHRED: "> 5"

#DeepRVAT model settings
n_repeats: 30
y_transformation: quantile_transform

# Results evaluation settings
evaluation:
  correction_method: Bonferroni
  alpha: 0.05
  center_scale_burdens: False

# Subsetting samples for association testing
#sample_files:
#  association_testing: association_testing_samples.pkl

#Additional settings if using the CV pipeline
cv_options:
  cv_exp: False
  #cv_path: sample_files
  #n_folds: 5

#Additional settings if using the REGENIE integration
regenie_options:
  regenie_exp: False
  # gtf_file: gencode.v38.basic.annotation.gtf.gz
  # step_1:
  #     bgen: imputation.bgen
  #     snplist: imputation.snplist
  #     bsize: 1000
  #     options:
  #         - "--sample imputation.sample"
  #         - "--qt"
  # step_2:
  #     bsize: 400
  #     options:
  #         - "--qt"