# Uncomment to use module load for required tools
#bcftools_load_cmd : module load bcftools/1.9
#htslib_load_cmd : module load htslib/1.9
#perl_load_cmd : module load perl/5.20.2
#vep_load_cmd : module load vep/108.1
fasta_dir : reference
fasta_file_name : GRCh38.primary_assembly.genome.fa
gtf_file_name : gencode.v44.annotation.gtf.gz
gene_id_parquet: reference/protein_coding_genes.parquet

source_variant_file_pattern :  chr{chr}test
source_variant_file_type: 'bcf'

# comment out / remove to run on all chromosomes
included_chromosomes : ['2','4']
annotation_columns_yaml_file: ../../example/config/annotation_colnames_filling_values_minimal.yaml
source_variant_dir : preprocessing_workdir/norm/bcf/
anno_tmp_dir : output_dir/annotations/tmp
anno_dir : output_dir/annotations
deepsea_pca_n_components: 7
vep_cache_dir : repo_dir/ensembl-vep/cache/
vep_plugin_dir : repo_dir/ensembl-vep/Plugins
deeprvat_repo_dir : ../..
kipoiveff_repo_dir : repo_dir/kipoi-veff2
faatpipe_repo_dir : repo_dir/faatpipe
vep_repo_dir : repo_dir/ensembl-vep
preprocessing_workdir : preprocessing_workdir

include_absplice : False
include_deepSEA : False
vep_online: True
vep_no_cache: True
