
# Phenotypes to calculate the seed gene baseline results for
phenotypes:
  - Apolipoprotein_A
  - Apolipoprotein_B
  - Calcium
  - Cholesterol
  - Red_blood_cell_erythrocyte_count
  - HDL_cholesterol
  - IGF_1
  - LDL_direct
  - Lymphocyte_percentage
  - Mean_platelet_thrombocyte_volume
  - Mean_corpuscular_volume
  - Mean_reticulocyte_volume
  - Neutrophill_count
  - Platelet_count
  - Platelet_crit
  - Platelet_distribution_width
  - SHBG
  - Standing_height
  - Total_bilirubin
  - Triglycerides
  - Urate

#File paths of necessary input files
gt_filename: genotypes.h5
variant_filename: variants.parquet
phenotype_filename: phenotypes.parquet
annotation_filename: annotations.parquet
gene_filename: protein_coding_genes.parquet

covariates: #x_phenotypes
  - age
  - age2
  - age_sex
  - genetic_sex
  - genetic_PC_1
  - genetic_PC_2
  - genetic_PC_3
  - genetic_PC_4
  - genetic_PC_5
  - genetic_PC_6
  - genetic_PC_7
  - genetic_PC_8
  - genetic_PC_9
  - genetic_PC_10
  - genetic_PC_11
  - genetic_PC_12
  - genetic_PC_13
  - genetic_PC_14
  - genetic_PC_15
  - genetic_PC_16
  - genetic_PC_17
  - genetic_PC_18
  - genetic_PC_19
  - genetic_PC_20

annotations:
    - MAF
    - is_plof
    - Consequence_missense_variant

test_types:
   - skat
   - burden

variant_types:
    - missense
    - plof

# Minor allele frequency threshold
rare_maf: 0.001

alpha_seed_genes: 0.05

test_config:
    center_genotype: True # center the genotype matrix
    neglect_homozygous: False # genotype value for homozygous variants: 1 (True) or 2 (False)
    collapse_method: sum # burden test collapsing method
    var_weight_function: beta_maf  # variant weighting function. Supported are beta_maf (Beta(MAF,1,25)) or sift_polyphen (mean of 1-SIFT and Polyphen2 score)
    min_mac: 10 # min expected allele count for genes to be included

dataset_config:
    standardize_xpheno: False
    y_transformation: quantile_transform

# Subsetting samples - Optional pickled list of samples to subset to
# sample_file: samples_list.pkl
