phenotypes:
    Calcium:
        correction_method: FDR
        n_training_genes: 100
        baseline_phenotype: Calcium

n_burden_chunks: 1

n_repeats: 6

do_scoretest: True

dnanexus:
  configfile: DeepRVAT/workdir/pretrained_scoring/config.yaml
  destination: DeepRVAT/workdir/pretrained_scoring
  applet: deeprvat_burdens
  priority: low

model:
    type: DeepSet
    model_collection: agg_models
    checkpoint: combined_agg.pt
    config:
        phi_layers: 2
        phi_hidden_dim: 20
        rho_layers: 3
        rho_hidden_dim: 10
        activation: LeakyReLU
        pool: max
        use_sigmoid: True
        metrics:
            objective: MSE
            objective_mode: min
            loss: MSE
            all:
                MSE: {}
                PearsonCorrTorch: {}
                MAE: {}
                RSquared: {}
        optimizer:
            type: AdamW
            config: {}

data:
    gt_file: genotypes.h5
    variant_file: variants_90pct10dp_qc.parquet
    dataset_config:
        min_common_af:
            combined_UKB_NFE_AF: 0.01
        phenotype_file: phenotypes.parquet
        y_transformation: quantile_transform
        x_phenotypes:
            - age
            - genetic_sex
            - genetic_PC_1
            - genetic_PC_2
            - genetic_PC_3
            - genetic_PC_4
            - genetic_PC_5
            - genetic_PC_6
            - genetic_PC_7
            - genetic_PC_8
            - genetic_PC_9
            - genetic_PC_10
            - genetic_PC_11
            - genetic_PC_12
            - genetic_PC_13
            - genetic_PC_14
            - genetic_PC_15
            - genetic_PC_16
            - genetic_PC_17
            - genetic_PC_18
            - genetic_PC_19
            - genetic_PC_20
        annotation_file: annotations.parquet
        annotations:
            - combined_UKB_NFE_AF
            - combined_UKB_NFE_AF_MB
            - CADD_PHRED
            - CADD_RAW
            - SIFT_score
            - PolyPhen_score
            - Consequence_splice_acceptor_variant
            - Consequence_splice_donor_variant
            - Consequence_stop_gained
            - Consequence_frameshift_variant
            - Consequence_stop_lost
            - Consequence_start_lost
            - Consequence_inframe_insertion
            - Consequence_inframe_deletion
            - Consequence_missense_variant
            - Consequence_protein_altering_variant
            - Consequence_splice_region_variant
            - Condel
            - DeepSEA_PC_1
            - DeepSEA_PC_2
            - DeepSEA_PC_3
            - DeepSEA_PC_4
            - DeepSEA_PC_5
            - DeepSEA_PC_6
            - PrimateAI
            - AbSplice_DNA
            - QKI_hg2
            - QKI_k5
            - KHDRBS1_k5
            - ELAVL1_parclip
            - TARDBP_parclip
            - HNRNPD_parclip
            - MBNL1_parclip
            - QKI_parclip
            - SpliceAI_delta
        gene_file: protein_coding_genes.parquet
        exclude_variant_cols:
            - 90pct10dp_qc
        use_common_variants: False
        use_rare_variants: True
        rare_embedding:
            type: PaddedAnnotations
            config:
                annotations:
                  - combined_UKB_NFE_AF_MB
                  - CADD_RAW
                  - SIFT_score
                  - PolyPhen_score
                  - Consequence_splice_acceptor_variant
                  - Consequence_splice_donor_variant
                  - Consequence_stop_gained
                  - Consequence_frameshift_variant
                  - Consequence_stop_lost
                  - Consequence_start_lost
                  - Consequence_inframe_insertion
                  - Consequence_inframe_deletion
                  - Consequence_missense_variant
                  - Consequence_protein_altering_variant
                  - Consequence_splice_region_variant
                  - Condel
                  - DeepSEA_PC_1
                  - DeepSEA_PC_2
                  - DeepSEA_PC_3
                  - DeepSEA_PC_4
                  - DeepSEA_PC_5
                  - DeepSEA_PC_6
                  - PrimateAI
                  - AbSplice_DNA
                  - QKI_hg2
                  - QKI_k5
                  - KHDRBS1_k5
                  - ELAVL1_parclip
                  - TARDBP_parclip
                  - HNRNPD_parclip
                  - MBNL1_parclip
                  - QKI_parclip
                  - SpliceAI_delta
                thresholds:
                    combined_UKB_NFE_AF: "combined_UKB_NFE_AF < 1e-3"
                    CADD_PHRED:  "CADD_PHRED > 5"
                gene_file: protein_coding_genes.parquet
                verbose: True
                low_memory: True
        verbose: True
    dataloader_config:
        batch_size: 16
        num_workers: 16
