fasta_dir : reference
fasta_file_name : hg38.fa
# Uncomment to use module load for required tools
#bcftools_load_cmd : module load bcftools/1.9
#htslib_load_cmd : module load htslib/1.9
#perl_load_cmd : module load perl/5.20.2
#vep_load_cmd : module load vep/108.1

source_variant_file_pattern : test_vcf_data_c{chr}_b{block}
source_variant_file_type: 'vcf.gz'

# comment out / remove to run on all chromosomes
included_chromosomes : ['21','22']

metadata_dir : input_dir/vcf/metadata
pvcf_blocks_file : pvcf_blocks.txt
source_variant_dir : input_dir/vcf
anno_tmp_dir : output_dir/annotations/tmp
anno_dir : output_dir/annotations

vep_cache_dir : repo_dir/ensembl-vep/cache/vep109
vep_plugin_dir : repo_dir/ensembl-vep/Plugins
spliceAI_snv_file : annotation_data/spliceAI/spliceai_scores.raw.snv.hg38.vcf.gz
spliceAI_indel_file : annotation_data/spliceAI/spliceai_scores.raw.indel.hg38.vcf.gz
primateAI_file : annotation_data/primateAI/PrimateAI_scores_v0.2_GRCh38_sorted.tsv.bgz
cadd_snv_file : annotation_data/cadd/whole_genome_SNVs.tsv.gz
cadd_indel_file : annotation_data/cadd/gnomad.genomes.r3.0.indel.tsv.gz
absplice_repo_dir : repo_dir/absplice
deeprvat_repo_dir : deeprvat_repo_dir
kipoiveff_repo_dir : repo_dir/kipoi-veff2
faatpipe_repo_dir : repo_dir/faatpipe
vep_repo_dir : repo_dir/ensembl-vep
vep_plugin_repo : repo_dir/VEP_plugins
variant_file_path : preprocessing_workdir/norm/variants/variants.tsv.gz
pybedtools_tmp_path : output_dir/annotations/tmp/pybedtools
n_jobs_deepripe : 32
n_cores_merge_absplice : 32
n_cores_absplice : 32
deepsea_pca_pickle_filepath : annotations/deepSea_pca/pca.pkl
deepsea_pca_n_components: 100
