fasta_dir : reference
fasta_file_name : GRCh38.primary_assembly.genome.fa.gz
bcftools_load_cmd : module load bcftools/1.9
htslib_load_cmd : module load htslib/1.9
perl_load_cmd : module load perl/5.20.2
vep_load_cmd : module load vep/108.1

vcf_file_pattern : ukb23156_c{chr}_b{block}_v1
included_chromosomes : ['21','22']

metadata_dir : vcf/metadata
pvcf_blocks_file : pvcf_blocks.txt
vcf_dir : vcf/raw
anno_tmp_dir : annotations/tmp
anno_dir : annotations

cadd_src_dir  : software/CADD-scripts
cadd_snv_file : annotation_data/cadd/whole_genome_SNVs.tsv.gz
cadd_indel_file : annotation_data/cadd/gnomad.genomes.r3.0.indel.tsv.gz
vep_src_dir : software/ensembl-vep
vep_cache_dir : software/ensembl-vep/cache/vep109
vep_plugin_dir : software/ensembl-vep/Plugins
spliceAI_snv_file : annotation_data/spliceAI/spliceai_scores.raw.snv.hg38.vcf.gz
spliceAI_indel_file : annotation_data/spliceAI/spliceai_scores.raw.indel.hg38.vcf.gz
primateAI_file : annotation_data/primateAI/PrimateAI_scores_v0.2_GRCh38_sorted.tsv.bgz




