# FROM mambaorg/micromamba:1.5.9-bookworm-slim
# 
# COPY --chown=$MAMBA_USER:$MAMBA_USER kipoi-veff2_env.yml /tmp/env.yml
# RUN micromamba create -v -y -f /tmp/env.yml && \
#     micromamba clean --all --yes



FROM mambaorg/micromamba:1.5.9
COPY --chown=$MAMBA_USER:$MAMBA_USER kipoi-veff2_env.yml /tmp/env.yaml
RUN micromamba install -y -n base -f /tmp/env.yaml && \
    micromamba clean --all --yes
