name: kipoi-veff2
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - snakemake
  - bedtools=2.30.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - click=8.1.3
  - coloredlogs=15.0.1
  - cython=0.29.23
  - cyvcf2=0.30.15
  - htslib=1.15.1
  - humanfriendly=10.0
  - importlib-metadata=4.11.3
  - keyutils=1.6.1
  - krb5=1.19.3
  - ld_impl_linux-64=2.36.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.83.0
  - libdeflate=1.10
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - liblapack=3.9.0
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libopenblas=0.3.20
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libzlib=1.2.11
  - ncurses=6.3
  - openssl=1.1.1n
  - pip=20.2.4
  - python=3.7.12
  - python_abi=3.7
  - readline=8.1
  - setuptools=62.1.0
  - sqlite=3.38.3
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.2.5
  - zipp=3.8.0
  - zlib=1.2.11
  - tensorflow=1.13.1
  - pybedtools
  - numpy=1.18.5
  - gcc=14.1.0
  - pip:
    - absl-py==1.0.0
    - argcomplete==2.0.0
    - argh==0.26.2
    - arrow==1.2.2
    - astor==0.8.1
    - attrs==21.4.0
    - binaryornot==0.4.4
    - certifi==2021.10.8
    - chardet==4.0.0
    - charset-normalizer==2.0.12
    - colorlog==6.6.0
    - cookiecutter==1.7.3
    - dataclasses==0.6
    - deprecation==2.1.0
    - future==0.18.2
    - gast==0.5.3
    - gffutils==0.10.1
    - grpcio==1.46.0
    - h5py==2.10.0
    - idna==3.3
    - iniconfig==1.1.1
    - jinja2==3.1.2
    - jinja2-time==0.2.0
    - keras==2.2.4
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kipoi==0.8.2
    - kipoi-conda==0.3.1
    - kipoi-utils==0.7.6
    - kipoiseq==0.7.1
    - markdown==3.3.6
    - markupsafe==2.1.1
    - mmsplice==2.2.0
    - mock==4.0.3
    - natsort==8.1.0
    - ncls==0.0.64
    - packaging==21.3
    - pandas==1.3.5
    - pluggy==1.0.0
    - poyo==0.5.0
    - protobuf==3.20.1
    - py==1.11.0
    - pyfaidx==0.6.4
    - pyparsing==3.0.8
    - pyranges==0.0.115
    - pyrle==0.0.34
    - pysam==0.16.0.1
    - pytest==7.1.2
    - python-dateutil==2.8.2
    - python-slugify==6.1.2
    - pytz==2022.1
    - pyyaml==6.0
    - related==0.7.2
    - requests==2.27.1
    - scikit-learn==0.19.2
    - scipy==1.5.4
    - simplejson==3.17.6
    - six==1.16.0
    - sorted-nearest==0.0.35
    - tabulate==0.8.9
    - termcolor==1.1.0
    - text-unidecode==1.3
    - tinydb==4.7.0
    - tomli==2.0.1
    - torch==1.11.0
    - tqdm==4.64.0
    - typing-extensions==4.1.1
    - urllib3==1.26.9
    - werkzeug==2.1.2
