splicing_pred:
  mmsplice_splicemap: '{genome}/model_scores_from_absplice_features/{vcf_id}_MMSplice_SpliceMap.csv'
  spliceai_vcf: '{genome}/model_scores_from_absplice_features/{vcf_id}_SpliceAI.vcf'
  spliceai: '{genome}/model_scores_from_absplice_features/{vcf_id}_SpliceAI.csv'
  absplice_dna: '{genome}/dna/{vcf_id}_AbSplice_DNA.csv'
  delta_psi_inferred_from_cat: '{genome}/model_scores_from_absplice_features/{vcf_id}_tissue_cat={tissue_cat}_delta_psi_inferred_from_cat.csv'
  cat_outliers: '{genome}/model_scores_from_absplice_features/{vcf_id}_tissue_cat={tissue_cat}_FRASER_pval.csv'
  absplice_rna: '{genome}/{vcf_id}_tissue_cat={tissue_cat}_AbSplice_RNA.csv'
  absplice_rna_with_dna_info: '{genome}/{vcf_id}_tissue_cat={tissue_cat}_AbSplice_all_info.csv'