name: spliceai-rocksdb
channels:
  - conda-forge
dependencies:
  - python==3.9.15
  - python-rocksdb==0.7.0
  - rocksdb==6.13.3
  - tensorflow-gpu==2.6.2
  - cudnn==8.8.0.121
  - cudatoolkit==11.0.3
  - pyarrow==6.0.1
  - tqdm==4.65.0
  - pip==23.2.1
  - setuptools==68.0.0
  - click==8.1.6
  - pooch==1.7.0
  - bioconda::snakemake==7.31.0
  - bioconda::kipoiseq==0.7.1
  - bioconda::spliceai==1.3.1
  - bioconda::cyvcf2==0.30.16
  - pip:
    - git+https://github.com/gagneurlab/spliceai_rocksdb.git@3c40d6e61b19e907e802c979c76d52ea5c41c1d5
