model:
    type: DeepSet
    model_collection: agg_models
    checkpoint: combined_agg.pt
    config:
        phi_layers: 2
        phi_hidden_dim: 20
        rho_layers: 3
        rho_hidden_dim: 10
        activation: LeakyReLU
        pool: max
        use_sigmoid: True
        metrics:
            objective: MSE
            objective_mode: min
            loss: MSE
            all:
                MSE: {}
                PearsonCorrTorch: {}
                MAE: {}
                RSquared: {}
        optimizer:
            type: AdamW
            config: {}
