
n_chunks: 15

#debug: True

data:
    dataset_config:
        use_common_variants: False
        use_rare_variants: True
        rare_embedding:
            config:
                verbose: True
        verbose: True
    dataloader_config:
        num_workers: 10
        #batch_size: 20
