name: "Pull Request Docs Check"
run-name: "Docs Check 📑📝"

on:
- pull_request

jobs:
  docs-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python 3.8
      uses: actions/setup-python@v6
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        pip install sphinx
        pip install -r docs/requirements.txt
    - name: Build documentation
      run: sphinx-build -M html docs docs-html

  # docs-link-check:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - uses: ammaraskar/sphinx-action@0.4
  #     with:
  #       docs-folder: "docs/"
  #       build-command: "make linkcheck"
