name: Run pipeline

on:
  workflow_call:
    inputs:
      environment_file:
        required: true
        type: string
      prerun_cmd:
        required: false
        type: string
      pipeline_file:
        required: true
        type: string
      name:
        required: true
        type: string
      no_gpu:
        required: false
        type: boolean
        default: true
      pipeline_directory:
        required: false
        type: string
        default: ./example
      pipeline_config:
        required: false
        type: string
      dry_run:
        required: false
        default: true
        type: boolean
      download_example_data:
        required: false
        default: false
        type: boolean
jobs:
  Run-Pipeline:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository code
          uses: actions/checkout@v4
        - uses: mamba-org/setup-micromamba@v1.8.1
          with:
            environment-name: pipeline-env
            environment-file: ${{inputs.environment_file}}
            cache-environment: true
            cache-downloads: true
        - name: Install DeepRVAT
          run: pip install -e ${{ github.workspace }}
          shell: micromamba-shell {0}
        - name: Cache Fasta file
          #if: inputs.download_example_data
          id: cache-fasta
          uses: actions/cache@v4
          with:
            path: ./example/preprocess/workdir/reference
            key: ${{ runner.os }}-reference-fasta
        - name: Download and unpack fasta data
          if: inputs.download_example_data && steps.cache-fasta.outputs.cache-hit != 'true'
          run: |
            wget https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_44/GRCh38.primary_assembly.genome.fa.gz \
            -O ./example/preprocess/workdir/reference/GRCh38.primary_assembly.genome.fa.gz \
            && gzip -d ./example/preprocess/workdir/reference/GRCh38.primary_assembly.genome.fa.gz
        - name: Run pre pipeline cmd
          if: inputs.prerun_cmd
          run: ${{inputs.prerun_cmd}}
          shell: bash -el {0}
        - name: Set to 0 Gpu in conf
          if: inputs.no_gpu
          # There are no GPUs on the gh worker, so we can disable it in the config
          run: "sed -i 's/gpus: 1/gpus: 0/' ./example/config.yaml"
          shell: bash -el {0}
        - name: ${{inputs.name}}
          run: |
            python -m snakemake ${{ (inputs.dry_run && '-n') || '' }} \
            -j 2 --directory ${{inputs.pipeline_directory}} \
            ${{ (endsWith(inputs.pipeline_config, 'ml') && '--configfile')  || '' }}  ${{ inputs.pipeline_config }} \
            --snakefile ${{inputs.pipeline_file}} --show-failed-logs -F  

          shell: micromamba-shell {0}
