name: Run pipeline

on:
  workflow_call:
    inputs:
      environment_file:
        required: true
        type: string
      prerun_cmd:
        required: false
        type: string
      pipeline_cmd:
        required: true
        type: string
      name:
        required: true
        type: string
      no_gpu:
        required: false
        type: boolean
        default: false

jobs:
  Run-Pipeline:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository code
          uses: actions/checkout@v4
        - uses: mamba-org/setup-micromamba@v1.8.1
          with:
            environment-name: pipeline-env
            environment-file: ${{inputs.environment_file}}
            cache-environment: true
            cache-downloads: true
        - name: Install DeepRVAT
          run: pip install -e ${{ github.workspace }}
          shell: micromamba-shell {0}
        - name: Run pre pipeline cmd
          if: inputs.prerun_cmd
          run: ${{inputs.prerun_cmd}}
          shell: bash -el {0}
        - name: Set to 0 Gpu in conf
          if: inputs.no_gpu
          # There are no GPUs on the gh worker, so we can disable it in the config
          run: "sed -i 's/gpus: 1/gpus: 0/' ./example/config.yaml"
          shell: bash -el {0}
        - name: ${{inputs.name}}
          run: ${{inputs.pipeline_cmd}}
          shell: micromamba-shell {0}
